language: julia
os:
  - linux
  - osx
julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("Gadfly");'
  - julia -e 'Pkg.checkout("Compose")'
  - julia --check-bounds=yes -e 'Pkg.test("Gadfly", coverage=true)'
after_success:
  - julia -e 'cd(Pkg.dir("Gadfly")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("Gadfly")); include(joinpath("docs", "make.jl"))'
